version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: steptogether-backend
    ports:
      - "8080:8080"
    restart: unless-stopped
