server:
  port: 8080

spring:
  application:
    name: backend

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

# ch? c?n ch? ??nh file service account
firebase:
  config:
    file: firebase-service-account.json
