server:
  port: 8080

spring:
  application:
    name: steptogether-backend

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

# Firebase Configuration
firebase:
  database-url: ${FIREBASE_URL:https://project-2025-ca63b-default-rtdb.firebaseio.com}
  service-account: ${FIREBASE_KEY_PATH:src/main/resources/firebase-service-account.json}

# WebSocket Configuration
websocket:
  allowed-origins: ${FRONTEND_URL:http://localhost:3000}

# CORS Configuration
cors:
  allowed-origins: ${FRONTEND_URL:http://localhost:3000}

# Logging Configuration
logging:
  level:
    com.steptogether: DEBUG
    org.springframework.web.socket: DEBUG
